### ISSUE TITLE
Issue with ':' in TwitchWrapper

### ISSUE THREAD

**Issue by Nyasaki** [scanf/snake#10]
Exception when a : appears in chat

**Comment by Nyasaki** [comment]
Fix with wile loop since the current solution counts only for 3 ':'

**Comment by scanf** [comment]
Hmm, totally forgot this bug. Was debugging for a while 🙈

**Comment by scanf** [comment]
Looks like we might get this merged soon, https://github.com/Talha-T/twitch-wrapper-ts/pull/7

**Comment by scanf** [comment]
Merged upstream.
