### ISSUE TITLE
Load default snakes for everyone in the chat

### ISSUE THREAD

**Issue by scanf** [scanf/snake#13]
While at it also remove the `.id` property from the snake, please.

**Comment by Mobilpadde** [comment]
8bd1503edb1c9c02e0dd449426b489baf8c80e4d closed #13

**Comment by Mobilpadde** [comment]
@scanf please review, whenever you have the time! :+1:

**Comment by scanf** [comment]
The changes don't break the build, but I still need to wait for the testing until someone new shows up in the chat.
