### ISSUE TITLE
Players get duplicated

### ISSUE THREAD

**Issue by scanf** [scanf/snake#19]
Review the avatar code in the `snake.ts`.

Reported-by: kvernknurren

**Comment by Mobilpadde** [comment]
Not happening on my branch, though I see it did happen to you on stream?

**Comment by scanf** [comment]
Weird, when did you test this? Was it during stream? Maybe it's timing dependent?

**Comment by scanf** [comment]
ok, tomorrow might be low traffic. I can help out testing and maybe @Nyasaki. 
Hmm, it might be happening when the user count is greater than `x`.
