### ISSUE TITLE
Watch twitch channel for !upload command

### ISSUE THREAD

**Issue by scanf** [scanf/snake#2]
When we get a `!upload`  command which must be in the below format, we perform input validation. If that passes it gets added to the list of to be executed in the game loop.

## Format

```
!upload ${gist_url}
```

## Error

Invalid scripts get rejected with a description on why.

**Comment by scanf** [comment]
Hmm, I am not sure what how much responsibility do we want to give the server. Should it tell the game clients changes to perform on snakes or do we want to go even further by providing it all information on what to actually draw on screen? What do you guys think?

**Comment by scanf** [comment]
Basically what I am asking is: `How much logic does the game client need?`

**Comment by Nyasaki** [comment]
Twitch Wrapper for Typescript
https://www.npmjs.com/package/twitch-wrapper-ts

**Comment by scanf** [comment]
Command is working now, thanks to @Nyasaki
