### ISSUE TITLE
Watch Twitch channel for !join command

### ISSUE THREAD

**Issue by scanf** [scanf/snake#4]
Add user to the team. If it does not exist, create it first and then add them.

## Format

```
!join ${team_name}
```

**Comment by Nyasaki** [comment]
@Nyasaki implemented it ^^

**Comment by scanf** [comment]
> On 14 Oct 2018, at 18:46, Marcel <notifications@github.com> wrote:
> 
> Closed #4.
> 

Great work, @nyasaki :+1:
