### ISSUE TITLE
Implement save button

### ISSUE THREAD

**Issue by Nyasaki** [scanf/snake#8]
Saving the current state (Teams, Scripts, etc.)

**Comment by scanf** [comment]
how about we use keybinding `CTRL-S` instead? Want to let the game take up the whole UI instead of adding buttons. Tried it earlier today and buttons don't look good with canvas combo.

**Comment by scanf** [comment]
We have dropped the team and join command, so not needed for saving.
The filesystem caching stuff handles scripts, so no need their. What's
missing from the UI is the bits for setting the Twitch credentials since the
game is now taking up the whole screen.
