### ISSUE TITLE
Use build service to detect new errors

### ISSUE THREAD

**Issue by scanf** [scanf/snake#9]
This should prevent master being unstable for too long.

**Comment by scanf** [comment]
Use travis or something.

**Comment by scanf** [comment]
You should just need to run

```
make install_deps
make build
```
The last call to build has to return a good exit code otherwise the build should fail.

**Comment by scanf** [comment]
```
```

**Comment by Nyasaki** [comment]
Could be closed if it runs without errors
>Build errors has to be fixed first

**Comment by scanf** [comment]
Working on the build issues, fix coming soon ;)

**Comment by scanf** [comment]
I couldn't fix it, @Mobilpadde is looking into it now.

**Comment by scanf** [comment]
The build is passing now, but we still have to fix the test scripts. Assigned to @Mobilpadde, not so familiar with the test environment.
